pid: tmp/pids/thin.pid
log: log/thin.log
timeout: 30
max_conns: 1024
port: 3000
max_persistent_conns: 512
chdir: /home/sevos/apps/logo-contest
environment: production
servers: 2
address: 127.0.0.1
daemonize: true
